//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPlus.Base.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPlus.Base.Resources.Localizations.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shared Parameters.
        /// </summary>
        public static string AddSharedParameter {
            get {
                return ResourceManager.GetString("AddSharedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply
        ///Schema.
        /// </summary>
        public static string ApplySchema {
            get {
                return ResourceManager.GetString("ApplySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task is currently being processed and is expected to complete within approximately 5 minutes.
        ///In the meantime, feel free to step away and take a short break!.
        /// </summary>
        public static string BreakInProgress {
            get {
                return ResourceManager.GetString("BreakInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Range.
        /// </summary>
        public static string ByRange {
            get {
                return ResourceManager.GetString("ByRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Value.
        /// </summary>
        public static string ByValue {
            get {
                return ResourceManager.GetString("ByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current document.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data link.
        /// </summary>
        public static string DataLink {
            get {
                return ResourceManager.GetString("DataLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data
        ///Schemas.
        /// </summary>
        public static string DataSchemas {
            get {
                return ResourceManager.GetString("DataSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Visualization.
        /// </summary>
        public static string DataVisualization {
            get {
                return ResourceManager.GetString("DataVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete schema.
        /// </summary>
        public static string DeleteSchema {
            get {
                return ResourceManager.GetString("DeleteSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Document version.
        /// </summary>
        public static string DocumentVersion {
            get {
                return ResourceManager.GetString("DocumentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONATE.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ElementAction {
            get {
                return ResourceManager.GetString("ElementAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElementId.
        /// </summary>
        public static string ElementId {
            get {
                return ResourceManager.GetString("ElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export report.
        /// </summary>
        public static string ExportReport {
            get {
                return ResourceManager.GetString("ExportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versioning.
        /// </summary>
        public static string FileVersioning {
            get {
                return ResourceManager.GetString("FileVersioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pattern.
        /// </summary>
        public static string FillPattern {
            get {
                return ResourceManager.GetString("FillPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.Plus.
        /// </summary>
        public static string GPlus {
            get {
                return ResourceManager.GetString("GPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include elements from links.
        /// </summary>
        public static string IncludeLinks {
            get {
                return ResourceManager.GetString("IncludeLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        public static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sync.
        /// </summary>
        public static string LastSync {
            get {
                return ResourceManager.GetString("LastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location
        ///Schemes.
        /// </summary>
        public static string LocationSchemas {
            get {
                return ResourceManager.GetString("LocationSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location scheme .
        /// </summary>
        public static string LocationScheme {
            get {
                return ResourceManager.GetString("LocationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Data Links.
        /// </summary>
        public static string ManageDataLinks {
            get {
                return ResourceManager.GetString("ManageDataLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage
        ///Links.
        /// </summary>
        public static string ManageLinks {
            get {
                return ResourceManager.GetString("ManageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Locations Schemes.
        /// </summary>
        public static string ManageLocationsSchemas {
            get {
                return ResourceManager.GetString("ManageLocationsSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Selected.
        /// </summary>
        public static string MergeSelected {
            get {
                return ResourceManager.GetString("MergeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data link.
        /// </summary>
        public static string NewDataLink {
            get {
                return ResourceManager.GetString("NewDataLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New location scheme.
        /// </summary>
        public static string NewLocationScheme {
            get {
                return ResourceManager.GetString("NewLocationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Excel table has new columns. 
        ///To add them as shared parameters, specify their type and proceed..
        /// </summary>
        public static string NewSharedParameter {
            get {
                return ResourceManager.GetString("NewSharedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Type.
        /// </summary>
        public static string PathType {
            get {
                return ResourceManager.GetString("PathType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To keep all our G.Algo tools free and fresh, we rely on your kind donations.
        ///If you find them useful, consider buying us a coffee!.
        /// </summary>
        public static string PayMeACoffeMessage {
            get {
                return ResourceManager.GetString("PayMeACoffeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay me
        ///a Coffee.
        /// </summary>
        public static string PayMeCoffee {
            get {
                return ResourceManager.GetString("PayMeCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous document.
        /// </summary>
        public static string PreviousVersion {
            get {
                return ResourceManager.GetString("PreviousVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string Pull {
            get {
                return ResourceManager.GetString("Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save
        ///Version.
        /// </summary>
        public static string SaveVersion {
            get {
                return ResourceManager.GetString("SaveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current state of the document as a new version of the model..
        /// </summary>
        public static string SaveVersionToolip {
            get {
                return ResourceManager.GetString("SaveVersionToolip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for links by schedule name..
        /// </summary>
        public static string SearchLink {
            get {
                return ResourceManager.GetString("SearchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scheme.
        /// </summary>
        public static string SelectScheme {
            get {
                return ResourceManager.GetString("SelectScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronized.
        /// </summary>
        public static string Synchronized {
            get {
                return ResourceManager.GetString("Synchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a break!.
        /// </summary>
        public static string TakeABreak {
            get {
                return ResourceManager.GetString("TakeABreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With G.algo tools, you save so much time that we honestly think you deserve to enjoy it.
        ///Go ahead, take a break! We’ve got you covered. No one will ever know..
        /// </summary>
        public static string TakeABreakMessage {
            get {
                return ResourceManager.GetString("TakeABreakMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a
        ///Break.
        /// </summary>
        public static string TakeBreak {
            get {
                return ResourceManager.GetString("TakeBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version
        ///Vistory.
        /// </summary>
        public static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the differences between the current document and a previous version..
        /// </summary>
        public static string VersioningToolTip {
            get {
                return ResourceManager.GetString("VersioningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize.
        /// </summary>
        public static string Visualize {
            get {
                return ResourceManager.GetString("Visualize", resourceCulture);
            }
        }
    }
}
