//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPlus.Base.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPlus.Base.Resources.Localizations.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the schema {0}?.
        /// </summary>
        public static string DeleteSchemaConfirmation {
            get {
                return ResourceManager.GetString("DeleteSchemaConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again, if the problem presists please contact our suport at: contact@g-algos.com.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save the file before proceeding..
        /// </summary>
        public static string FirstSaveFile {
            get {
                return ResourceManager.GetString("FirstSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization parameter is not valid. It may have been deleted from the project..
        /// </summary>
        public static string LocalizationNotValid {
            get {
                return ResourceManager.GetString("LocalizationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Category is not valid..
        /// </summary>
        public static string LocCategorieMissing {
            get {
                return ResourceManager.GetString("LocCategorieMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization name cannot be empty..
        /// </summary>
        public static string LocNameMissing {
            get {
                return ResourceManager.GetString("LocNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization parameter is not valid..
        /// </summary>
        public static string LocParamMissing {
            get {
                return ResourceManager.GetString("LocParamMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a path..
        /// </summary>
        public static string MissingPath {
            get {
                return ResourceManager.GetString("MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were detected..
        /// </summary>
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No localization schemes available. Please create a localization scheme to proceed..
        /// </summary>
        public static string NoLocalizations {
            get {
                return ResourceManager.GetString("NoLocalizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule name cannot be empty..
        /// </summary>
        public static string NoSchedule {
            get {
                return ResourceManager.GetString("NoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must contain only letters..
        /// </summary>
        public static string OnlyStrings {
            get {
                return ResourceManager.GetString("OnlyStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOOps!!! Something Went Wrong!.
        /// </summary>
        public static string OOOps {
            get {
                return ResourceManager.GetString("OOOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Failed.
        /// </summary>
        public static string PullFailed {
            get {
                return ResourceManager.GetString("PullFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Failed.
        /// </summary>
        public static string PushFailed {
            get {
                return ResourceManager.GetString("PushFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait!!!.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
